#                 *************************************************************
#                 *             Start of HA System Configuration              *
#                 *************************************************************

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
ios:
sun:

#Basic information setup
homeassistant:
  latitude: !secret homelatitude
  longitude: !secret homelongitude
  elevation: !secret homeelevation
  time_zone: !secret hometimezone
  name: !secret homename

  #Set unit system (metric or imperial)
  unit_system: metric

  #List of folders that can be used as sources for sending files.
  whitelist_external_dirs:
    - /config

#Discovery options
discovery:
  ignore:
    - plex_mediaserver
#Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  #base_url: !secret baseurl
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

#Set Lovelace in YAML mode as opposed to design.
lovelace:
  mode: yaml

#Set Lovelace Frontend options
frontend:
  themes: !include_dir_merge_named themes

#Set Notify options in order to send notifications to a wide variety of platforms.
notify:
  - name: homeassistantmail
    platform: smtp
    server: !secret notifysmtpserveraddress
    port: !secret notifysmtpserverport
    timeout: 15
    sender: !secret notifysenderaddress
    encryption: starttls
    username: !secret notifygmailusername
    password: !secret notifygmailpassword
    recipient: 
      - !secret notifyrecipientaddress1
      - !secret notifyrecipientaddress2
    sender_name: Maison

#Additional panels to frontend (sidebar)
panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave

# Uncomment this for detailed logging
#logger:

#                 *************************************************************
#                 *              End of HA System Configuration               *
#                 *************************************************************



#                 *************************************************************
#                 *           Start of Home Assistant Integrations            *
#                 *************************************************************

#Elk M1 Gold Alarm System
elkm1:
  host: !secret elkm1goldaddress
  username: !secret elkm1goldusername
  password: !secret elkm1goldpassword
  area:
    exclude: [2-8]
  counter:
    exclude: [1-64]
  keypad:
    exclude: [2-16]
  output:
    exclude: [1-208]
  plc:
    exclude: [1-256]
  setting:
    exclude: [1-20]
  task:
    exclude: [1-32]
  thermostat:
    exclude: [1-16]
  zone:
    exclude: [16-208]

#Universal-Devices ISY-994
isy994:
  host: !secret isy994address
  username: !secret isy994username
  password: !secret isy994password

#LIFX RGB Bulbs
lifx:
  light:
    - broadcast: !secret lifx_gu10_bulb_ip_address_1
    - broadcast: !secret lifx_gu10_bulb_ip_address_2

#MQTT
mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_username
  password: !secret mqtt_password

#Plex Media Server
plex:
  host: !secret plex_ip_address
  token: !secret plex_token

#SpeedTest
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

#Z-Wave
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwavenetworkkey
  device_config: !include zwave_device_config.yaml

#                 *************************************************************
#                 *            End of Home Assistant Integrations             *
#                 *************************************************************



#                 *************************************************************
#                 *                Start of Custom Components                 *
#                 *************************************************************

docker_monitor:
  scan_interval: 10
  containers:
    - home-assistant
    - appdaemon-home-assistant
    - sftp
    - portainer
    - owntracks
    - mosquitto
  monitored_conditions:
    - utilization_version
    - container_status
    - container_uptime
    - container_memory_usage
    - container_memory_percentage_usage
    - container_cpu_percentage_usage

#                 *************************************************************
#                 *                 End of Custom Components                  *
#                 *************************************************************



#                 *************************************************************
#                 *           Start of Configuration File splitting           *
#                 *************************************************************

automation: !include configuration/automations.yaml
group: !include configuration/groups.yaml
light: !include configuration/lights.yaml
media_player: !include configuration/media_player.yaml
script: !include configuration/scripts.yaml
sensor: !include configuration/sensors.yaml
switch: !include configuration/switchs.yaml
zone: !include configuration/zones.yaml

#                 *************************************************************
#                 *            End of Configuration File splitting            *
#                 *************************************************************