    title: Security
    icon: mdi:security
    cards:
        # The markdown card will render markdown text.
      - type: alarm-panel
        name: House Alarm (Elk M1 Gold)
        entity: alarm_control_panel.area_001
      - type: entities
        entities:
          - sensor.elkm1
          - sensor.zone_005
          - sensor.zone_006
        show_header_toggle: false
        title: Alarm Components
      - type: entities
        entities:
          - sensor.elkm1
          - sensor.zone_001
          - sensor.zone_002
          - sensor.zone_003
          - sensor.zone_004
          - sensor.zone_005
          - sensor.zone_006
          - sensor.zone_007
          - sensor.zone_008
          - sensor.zone_009
          - sensor.zone_010
          - sensor.zone_011
          - sensor.zone_012
          - sensor.zone_013
          - sensor.zone_014
          - sensor.zone_015
        show_header_toggle: false
        title: Alarm Zones
      - type: custom:card-modder
        card:    
          type: alarm-panel
          name: House Alarm (Elk M1 Gold) Custom
          entity: alarm_control_panel.area_001
        style:
          background-image: url("/local/background-lovelace/cardbackK.png")              
          background-repeat: no-repeat                                      
          background-color: rgba(0,0,0,0.0)
          background-size: 100% 100%
          border-radius: 20px
          border: solid 1px rgba(100,100,100,0.3)
          color: grey
          box-shadow: 5px 5px rgba(0,0,0,0.6)